// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowserOpenURL(arg1) {
  return window['go']['main']['App']['BrowserOpenURL'](arg1);
}

export function Invoke(arg1, arg2) {
  return window['go']['main']['App']['Invoke'](arg1, arg2);
}

export function ShowOpenDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowOpenDialog'](arg1, arg2);
}

export function ShowSaveDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowSaveDialog'](arg1, arg2, arg3);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsMaximized() {
  return window['go']['main']['App']['WindowIsMaximized']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowToggleMaximize() {
  return window['go']['main']['App']['WindowToggleMaximize']();
}
