// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowserOpenURL(arg1:string):Promise<void>;

export function Invoke(arg1:string,arg2:Record<string, any>):Promise<any>;

export function ShowOpenDialog(arg1:string,arg2:Array<any>):Promise<string>;

export function ShowSaveDialog(arg1:string,arg2:string,arg3:Array<any>):Promise<string>;

export function WindowClose():Promise<void>;

export function WindowIsMaximized():Promise<boolean>;

export function WindowMinimize():Promise<void>;

export function WindowToggleMaximize():Promise<void>;
